apiVersion: v2
name: mx-infra
description: Infra for mx
type: application
version: 0.1.1
appVersion: "1.3.50.0"
icon: https://bicarus-labs.github.io/helm-charts/charts/mx-infra/icon.400x400.png
dependencies:
  - name: opensearch
    version: 2.9.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.enabled
  - name: opensearch-dashboards
    version: 2.7.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch-dashboards.enabled
  - name: rabbitmq
    version: 11.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: mysql
    condition: mysql.enabled
    version: 9.4.5
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    condition: redis.enabled
    version: 17.3.17
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    condition: mongodb.enabled
    version: 13.6.3
    repository: https://charts.bitnami.com/bitnami
  - name: mx-notifier
    condition: mx-notifier.enabled
    version: 1.1.9
    repository: file://../mx-notifier
  