apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-2-s3.fullname" . }}-s3-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.s3.region | b64enc }}